### ISSUE TITLE
UUID4 with milliseconds ?

### ISSUE THREAD

**Issue by andrewtw** [tcjennings/LUA-RFC-4122-UUID-Generator#5]
Hi,
I found **os.time()** is used as input variable in **math.randomseed()**, 
however, this only gives the full second of the current time.
I wonder whether we could generate a higher precise time in milliseconds without using the **LuaSocket**, can you give some suggestions?

**Comment by tcjennings** [comment]
You can't get better than second resolution with the functions in base Lua, as far as I know, but you might be able to salt that value with os.clock().

One goal of this code was to produce UUIDs with base Lua. I would go ahead and use the appropriate extension to produce the results you need.

**Comment by shakesoda** [comment]
Try os.clock()

**Comment by tcjennings** [comment]
You can't use os.clock() by itself since math.randomseed() doesn't use float seeds.

```lua
> print( os.clock() )
0.0077
> math.randomseed( 0.0077 )        
> print( math.random() )
0.013469574513598
> print( math.random() )
0.38313885004406
> print( os.clock() )
0.00835
> math.randomseed( 0.00835 )
> print( math.random() )
0.013469574513598
> print( math.random() )
0.38313885004406
> math.randomseed( 0 )
> print( math.random() )
0.013469574513598
```

**Comment by shakesoda** [comment]
Sure, but something like (os.time() + os.clock()) * 1000 should work.

**Comment by tcjennings** [comment]
That's about as good as you can do, but depending on the application it might not be appropriate. It's dependent on the specific implementation whether os.clock() gets you enough salt to be worth the effort.
