### ISSUE TITLE
Not nearly random

### ISSUE THREAD

**Issue by deric** [tcjennings/LUA-RFC-4122-UUID-Generator#6]
`test.lua`:
```
local uuid4= require("uuid4")
print( os.time() )
print( uuid4.getUUID() )
print( uuid4.getUUID() )
```
when executed within same second, the UUIDs will be the same
```
$ lua test.lua
1494495567
8BD3C9EE-AC73-4D97-B8DB-F62589C123B0
14B9CDA3-F9FD-4159-A422-5021AE32C3DB
$ lua test.lua
1494495568
5D84393C-6520-4359-ABA9-0B27B3A7312F
434E11D0-AAF9-4BF0-89EF-040168ACF98D
$ lua test.lua
1494495568
5D84393C-6520-4359-ABA9-0B27B3A7312F
434E11D0-AAF9-4BF0-89EF-040168ACF98D
```
It would be better to base the random seed on nanoseconds time.

**Comment by tcjennings** [comment]
Lua does not have nanosecond time. If you want nanosecond time, you must introduce a dependency on a module or package that provides it, otherwise manage your random seed outside the loop that generates the UUIDs.

**Comment by tcjennings** [comment]
Note, this is only an issue if you're loading the module more than once per second, since the seed is set when the module is loaded, not when a UUID is generated.
